export const COMPONENTS = [
  {
    id: "top-grille",
    index: "01",
    name: "Top air grille",
    category: "Structure",
    color: "#a7bac4",
    role: "Protects the fan while directing cleaned air upward in a low-turbulence spiral.",
    material: "Recycled ABS",
    service: "Quarter-turn bayonet mount; remove before accessing the airflow stack.",
    metric: "38% quieter outlet",
    risk: "Low",
    order: 1,
  },
  {
    id: "left-shell",
    index: "02",
    name: "Left enclosure",
    category: "Structure",
    color: "#d9e3e6",
    role: "Structural half-shell with a ribbed inner frame that protects the filter chamber.",
    material: "PC–ABS blend",
    service: "Release the two base clips, then slide vertically. No adhesive is used.",
    metric: "1.8 mm wall",
    risk: "Low",
    order: 2,
  },
  {
    id: "right-shell",
    index: "03",
    name: "Right enclosure",
    category: "Structure",
    color: "#8da4ae",
    role: "Service-side shell carrying the sensor inlet and tactile alignment marks.",
    material: "PC–ABS blend",
    service: "Remove after the top grille. Pull from the marked lower edge.",
    metric: "2 service clips",
    risk: "Low",
    order: 2,
  },
  {
    id: "pre-filter",
    index: "04",
    name: "Washable pre-filter",
    category: "Airflow",
    color: "#65d5c1",
    role: "Captures hair and coarse dust before air reaches the fine-particle filter.",
    material: "PET mesh",
    service: "Rinse every four weeks and dry fully before reinstalling.",
    metric: "250 μm mesh",
    risk: "Low",
    order: 3,
  },
  {
    id: "hepa-filter",
    index: "05",
    name: "H13 filter core",
    category: "Airflow",
    color: "#f0d283",
    role: "Pleated media removes fine particulate matter from the incoming air stream.",
    material: "Glass-fiber composite",
    service: "Replace when pressure drop exceeds 180 Pa; do not wash.",
    metric: "99.95% at 0.3 μm",
    risk: "Low",
    order: 4,
  },
  {
    id: "fan-rotor",
    index: "06",
    name: "Mixed-flow impeller",
    category: "Airflow",
    color: "#50d8ee",
    role: "Seven swept blades balance high static pressure with low audible turbulence.",
    material: "Glass-filled nylon",
    service: "Inspect for dust imbalance and blade damage; never bend the blades.",
    metric: "2,400 RPM",
    risk: "Moving part",
    order: 5,
  },
  {
    id: "motor",
    index: "07",
    name: "Brushless motor",
    category: "Power",
    color: "#f3a65a",
    role: "Drives the impeller with closed-loop speed control from the main board.",
    material: "Copper / steel",
    service: "Disconnect power before handling. Bearings are sealed for life.",
    metric: "18 W peak",
    risk: "Electrical",
    order: 6,
  },
  {
    id: "sensor-board",
    index: "08",
    name: "Air-quality sensor",
    category: "Electronics",
    color: "#9c8cff",
    role: "Measures particulate concentration, temperature, and humidity at the intake.",
    material: "FR-4 / silicon",
    service: "Clean the optical channel with dry air only; avoid touching the lens.",
    metric: "PM1.0–PM10",
    risk: "ESD sensitive",
    order: 7,
  },
  {
    id: "controller-board",
    index: "09",
    name: "Control board",
    category: "Electronics",
    color: "#67db87",
    role: "Combines sensor data, fan control, filter-life estimation, and wireless status.",
    material: "FR-4 / copper",
    service: "Disconnect the battery first. Handle only by the board edges.",
    metric: "32-bit MCU",
    risk: "ESD sensitive",
    order: 8,
  },
  {
    id: "battery-pack",
    index: "10",
    name: "Backup battery",
    category: "Power",
    color: "#ff7979",
    role: "Provides safe shutdown and short portable operation during power interruption.",
    material: "LiFePO₄ cells",
    service: "Inspect for swelling. Replace only with the specified protected pack.",
    metric: "12.8 V · 1.5 Ah",
    risk: "Stored energy",
    order: 9,
  },
];

export const GUIDE_STEPS = [
  {
    kicker: "SYSTEM OVERVIEW",
    title: "One product. Every layer.",
    description: "Rotate the assembled AeroCore, select a component, or follow this guided teardown.",
    explosion: 0,
    partId: null,
  },
  {
    kicker: "STEP 01 · ACCESS",
    title: "Open without tools.",
    description: "The top grille and split enclosure use reversible clips—faster service with no hidden screws.",
    explosion: 0.28,
    partId: "top-grille",
  },
  {
    kicker: "STEP 02 · FILTRATION",
    title: "Follow the air path.",
    description: "Coarse debris stops at the washable mesh before the H13 core captures fine particles.",
    explosion: 0.5,
    partId: "hepa-filter",
  },
  {
    kicker: "STEP 03 · AIRFLOW",
    title: "Pressure without the noise.",
    description: "A seven-blade mixed-flow impeller draws air evenly through the cylindrical filter.",
    explosion: 0.68,
    partId: "fan-rotor",
  },
  {
    kicker: "STEP 04 · INTELLIGENCE",
    title: "Sense, decide, adapt.",
    description: "The optical sensor and control board adjust fan speed to actual room conditions.",
    explosion: 0.86,
    partId: "controller-board",
  },
  {
    kicker: "STEP 05 · SERVICE",
    title: "Designed for a second life.",
    description: "Every high-wear module separates cleanly, helping technicians repair instead of replace.",
    explosion: 1,
    partId: "battery-pack",
  },
];

export const SERVICE_SEQUENCE = [
  "top-grille",
  "right-shell",
  "pre-filter",
  "hepa-filter",
  "battery-pack",
];

export const CATEGORY_COLORS = {
  Structure: "#a7bac4",
  Airflow: "#50d8ee",
  Electronics: "#9c8cff",
  Power: "#ff9e64",
  Propulsion: "#45d6ed",
  Imaging: "#d999ff",
  Drive: "#f4b45f",
  Sensing: "#8f9cff",
};

export const DRONE_COMPONENTS = [
  {
    id: "drone-canopy",
    index: "01",
    name: "Aerodynamic canopy",
    category: "Structure",
    color: "#dce7eb",
    role: "Protects the avionics while guiding cooling air over the central electronics stack.",
    material: "Impact-resistant polycarbonate",
    service: "Release four quarter-turn clips and lift vertically without pulling the antenna lead.",
    metric: "82 g shell",
    risk: "Low",
    order: 1,
  },
  {
    id: "drone-frame",
    index: "02",
    name: "Carbon center frame",
    category: "Structure",
    color: "#536874",
    role: "Transfers motor loads through a rigid sandwich frame while protecting the battery bay.",
    material: "Carbon-fiber laminate",
    service: "Inspect around arm roots for white stress marks or delamination.",
    metric: "4 mm laminate",
    risk: "Sharp edges",
    order: 2,
  },
  {
    id: "drone-arms",
    index: "03",
    name: "Foldable arm set",
    category: "Structure",
    color: "#8399a5",
    role: "Positions the four motors and folds inward for transport without disconnecting wiring.",
    material: "Glass-filled nylon",
    service: "Check hinge play and replace any arm that no longer locks positively.",
    metric: "4 locking hinges",
    risk: "Pinch point",
    order: 3,
  },
  {
    id: "drone-propellers",
    index: "04",
    name: "Propeller set",
    category: "Propulsion",
    color: "#66e4ed",
    role: "Matched clockwise and counter-clockwise blades generate lift and attitude control.",
    material: "Carbon-reinforced polymer",
    service: "Replace blades as matched pairs after any impact or visible edge damage.",
    metric: "9.4 inch",
    risk: "Moving part",
    order: 1,
  },
  {
    id: "drone-motors",
    index: "05",
    name: "Brushless motor set",
    category: "Propulsion",
    color: "#f0a45e",
    role: "Four outrunner motors convert battery power into independently controlled thrust.",
    material: "Aluminum / copper",
    service: "Rotate by hand and check for bearing roughness before reconnecting power.",
    metric: "920 kV",
    risk: "Electrical",
    order: 4,
  },
  {
    id: "drone-controller",
    index: "06",
    name: "Flight controller",
    category: "Electronics",
    color: "#67d985",
    role: "Fuses inertial, GPS, and pilot inputs to stabilize the aircraft hundreds of times per second.",
    material: "FR-4 / silicon",
    service: "Use ESD protection and preserve the vibration-isolation mounts.",
    metric: "1 kHz control loop",
    risk: "ESD sensitive",
    order: 6,
  },
  {
    id: "drone-gps",
    index: "07",
    name: "GPS and compass",
    category: "Sensing",
    color: "#9a91ff",
    role: "Provides global position and heading for navigation, return-to-home, and geofencing.",
    material: "Ceramic / FR-4",
    service: "Keep high-current motor wires away from the compass module during reassembly.",
    metric: "Dual-band GNSS",
    risk: "Magnetic sensitivity",
    order: 5,
  },
  {
    id: "drone-camera",
    index: "08",
    name: "Stabilized camera",
    category: "Imaging",
    color: "#d48cf1",
    role: "A three-axis gimbal isolates the imaging sensor from aircraft pitch, roll, and vibration.",
    material: "Magnesium / glass",
    service: "Lock the gimbal before transport and never force an axis by hand.",
    metric: "4K / 60 fps",
    risk: "Fragile optics",
    order: 7,
  },
  {
    id: "drone-battery",
    index: "09",
    name: "Flight battery",
    category: "Power",
    color: "#ff7474",
    role: "A high-discharge smart battery supplies propulsion and monitors cell health.",
    material: "Li-ion polymer",
    service: "Remove first, inspect for swelling, and store near 50 percent charge.",
    metric: "14.8 V / 5 Ah",
    risk: "Stored energy",
    order: 2,
  },
  {
    id: "drone-gear",
    index: "10",
    name: "Landing gear",
    category: "Structure",
    color: "#9fb1ba",
    role: "Keeps the camera clear of the ground and absorbs routine landing loads.",
    material: "Fiber-reinforced nylon",
    service: "Confirm both skids sit level and replace cracked mounting clips.",
    metric: "120 mm clearance",
    risk: "Low",
    order: 3,
  },
];

export const DRONE_GUIDE_STEPS = [
  {
    kicker: "AIRCRAFT OVERVIEW",
    title: "A flying control system.",
    description: "Explore how structure, sensing, propulsion, imaging, and stored energy work together.",
    explosion: 0,
    partId: null,
  },
  {
    kicker: "STEP 01 · SAFETY",
    title: "Make propulsion safe.",
    description: "The battery and matched propeller set are the first items handled before deeper service.",
    explosion: 0.24,
    partId: "drone-battery",
  },
  {
    kicker: "STEP 02 · STRUCTURE",
    title: "Loads meet at the center.",
    description: "Foldable arms transfer thrust into a stiff carbon center frame.",
    explosion: 0.45,
    partId: "drone-frame",
  },
  {
    kicker: "STEP 03 · PROPULSION",
    title: "Four motors, one attitude.",
    description: "Independent motor speeds control lift, roll, pitch, and yaw.",
    explosion: 0.65,
    partId: "drone-motors",
  },
  {
    kicker: "STEP 04 · NAVIGATION",
    title: "Sense before acting.",
    description: "The flight controller combines inertial motion with GPS and compass data.",
    explosion: 0.84,
    partId: "drone-controller",
  },
  {
    kicker: "STEP 05 · IMAGING",
    title: "Keep the horizon steady.",
    description: "The camera gimbal cancels aircraft motion while preserving a lightweight optical payload.",
    explosion: 1,
    partId: "drone-camera",
  },
];

export const DRIVE_COMPONENTS = [
  {
    id: "drive-front-cover",
    index: "01",
    name: "Output-side cover",
    category: "Structure",
    color: "#c9d8de",
    role: "Protects the precision gear and supports the main output bearing.",
    material: "Machined aluminum",
    service: "Loosen bolts in a cross pattern to avoid distorting the bearing seat.",
    metric: "IP65 seal",
    risk: "Low",
    order: 1,
  },
  {
    id: "drive-rear-housing",
    index: "02",
    name: "Motor housing",
    category: "Structure",
    color: "#738995",
    role: "Carries the stator, rear bearing, cooling ribs, and cable interface.",
    material: "Die-cast aluminum",
    service: "Inspect cooling fins and mating faces before applying a new gasket.",
    metric: "2.6 kg housing",
    risk: "Heavy part",
    order: 1,
  },
  {
    id: "drive-output",
    index: "03",
    name: "Output flange",
    category: "Drive",
    color: "#63d8e8",
    role: "Transfers high-torque, low-speed motion from the reducer to the robot link.",
    material: "Hardened steel",
    service: "Mark its angular position before removal to preserve calibration.",
    metric: "120 Nm peak",
    risk: "Pinch point",
    order: 2,
  },
  {
    id: "drive-wave-gear",
    index: "04",
    name: "Strain-wave reducer",
    category: "Drive",
    color: "#efc96d",
    role: "A flexible spline and elliptical wave generator create a compact high reduction ratio.",
    material: "Hardened alloy steel",
    service: "Keep matched gear elements together and protect their tooth surfaces.",
    metric: "80:1 ratio",
    risk: "Precision surface",
    order: 4,
  },
  {
    id: "drive-rotor",
    index: "05",
    name: "Permanent-magnet rotor",
    category: "Drive",
    color: "#ef8e57",
    role: "Rotating magnets interact with the stator field to generate joint torque.",
    material: "Steel / NdFeB",
    service: "Use a nonmagnetic fixture; the rotor can pull tools into the air gap.",
    metric: "16-pole rotor",
    risk: "Strong magnet",
    order: 5,
  },
  {
    id: "drive-stator",
    index: "06",
    name: "Motor stator",
    category: "Power",
    color: "#d66f5f",
    role: "Three-phase copper windings generate the rotating magnetic field.",
    material: "Copper / electrical steel",
    service: "Check insulation and phase resistance before reinstalling the rotor.",
    metric: "48 V three-phase",
    risk: "Electrical",
    order: 5,
  },
  {
    id: "drive-encoder",
    index: "07",
    name: "Absolute encoder",
    category: "Sensing",
    color: "#9a8cff",
    role: "Measures joint angle immediately at power-up without requiring a homing move.",
    material: "FR-4 / optical glass",
    service: "Prevent dust from reaching the code disc and do not rotate it separately.",
    metric: "19-bit position",
    risk: "ESD sensitive",
    order: 6,
  },
  {
    id: "drive-controller",
    index: "08",
    name: "Servo controller",
    category: "Electronics",
    color: "#63d27d",
    role: "Closes current, velocity, and position loops while monitoring thermal limits.",
    material: "FR-4 / silicon",
    service: "Discharge the DC bus and handle the board only by its edges.",
    metric: "20 kHz current loop",
    risk: "Stored charge",
    order: 7,
  },
  {
    id: "drive-brake",
    index: "09",
    name: "Holding brake",
    category: "Power",
    color: "#f1ad58",
    role: "A spring-applied brake holds the robot joint safely when electrical power is removed.",
    material: "Steel / friction composite",
    service: "Measure air gap and never lubricate the friction surfaces.",
    metric: "45 Nm holding",
    risk: "Spring force",
    order: 6,
  },
  {
    id: "drive-cable-hub",
    index: "10",
    name: "Cable and seal hub",
    category: "Structure",
    color: "#97abb4",
    role: "Routes power, data, and brake wiring through a sealed rear interface.",
    material: "Aluminum / elastomer",
    service: "Replace compressed seals and verify strain relief before operation.",
    metric: "Hybrid connector",
    risk: "Low",
    order: 3,
  },
];

export const DRIVE_GUIDE_STEPS = [
  {
    kicker: "JOINT OVERVIEW",
    title: "Torque, sensing, and safety.",
    description: "Inspect a compact robotic joint from its output flange to the servo electronics.",
    explosion: 0,
    partId: null,
  },
  {
    kicker: "STEP 01 · OUTPUT",
    title: "Start where torque leaves.",
    description: "The flange and output bearing carry both robot loads and reducer torque.",
    explosion: 0.25,
    partId: "drive-output",
  },
  {
    kicker: "STEP 02 · REDUCTION",
    title: "Precision through flexibility.",
    description: "A strain-wave reducer creates high ratio and near-zero backlash in a compact volume.",
    explosion: 0.48,
    partId: "drive-wave-gear",
  },
  {
    kicker: "STEP 03 · MOTOR",
    title: "Electromagnetism becomes motion.",
    description: "The stator field pulls the permanent-magnet rotor around the joint axis.",
    explosion: 0.68,
    partId: "drive-rotor",
  },
  {
    kicker: "STEP 04 · FEEDBACK",
    title: "Know the angle immediately.",
    description: "An absolute encoder closes the position loop without a startup homing cycle.",
    explosion: 0.86,
    partId: "drive-encoder",
  },
  {
    kicker: "STEP 05 · SAFE HOLD",
    title: "Fail safely without power.",
    description: "The spring-applied brake holds the joint whenever electrical power is removed.",
    explosion: 1,
    partId: "drive-brake",
  },
];

export const MODEL_LIBRARY = {
  aerocore: {
    id: "aerocore",
    name: "AeroCore",
    variant: "S1",
    code: "AC-01",
    subtitle: "Adaptive air-quality module",
    description: "Airflow, filtration, sensing, and serviceability.",
    components: COMPONENTS,
    guideSteps: GUIDE_STEPS,
    serviceSequence: SERVICE_SEQUENCE,
    initialRotation: [0, -0.28, 0],
    studioCamera: [7.3, 4.8, 10],
    arYOffset: 2.03,
    arSurfaceScale: 0.14,
    arMarkerScale: 0.22,
  },
  skyscout: {
    id: "skyscout",
    name: "SkyScout",
    variant: "Q4",
    code: "SS-04",
    subtitle: "Autonomous imaging quadcopter",
    description: "Flight control, propulsion, sensing, and imaging.",
    components: DRONE_COMPONENTS,
    guideSteps: DRONE_GUIDE_STEPS,
    serviceSequence: [
      "drone-battery",
      "drone-propellers",
      "drone-canopy",
      "drone-gps",
      "drone-controller",
    ],
    initialRotation: [0.08, 0.55, 0],
    studioCamera: [6.8, 5.4, 8.2],
    arYOffset: 1.62,
    arSurfaceScale: 0.105,
    arMarkerScale: 0.15,
  },
  vectordrive: {
    id: "vectordrive",
    name: "VectorDrive",
    variant: "R3",
    code: "VD-03",
    subtitle: "Precision robotic joint actuator",
    description: "Motor torque, precision reduction, feedback, and braking.",
    components: DRIVE_COMPONENTS,
    guideSteps: DRIVE_GUIDE_STEPS,
    serviceSequence: [
      "drive-cable-hub",
      "drive-rear-housing",
      "drive-brake",
      "drive-encoder",
      "drive-controller",
    ],
    initialRotation: [0.1, -0.45, -0.08],
    studioCamera: [5.8, 3.5, 7.4],
    arYOffset: 1.5,
    arSurfaceScale: 0.13,
    arMarkerScale: 0.19,
  },
};

export const MODEL_IDS = Object.keys(MODEL_LIBRARY);
